In [1]:
import numpy as np

### it generates the random array using "randint()", we pass lower,higher values and size of array

In [63]:
arr1 = np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr1

array([[89, 36, 81, 79, 77],
       [50, 24, 78, 49,  4],
       [51, 16, 16, 16, 28],
       [63, 23,  6, 11,  9]])

### conditional indexing

In [64]:
# Q. we only fetch those elements who is greater than 50

arr1>50    

#every elements compared with 50 & return boolean array

array([[ True, False,  True,  True,  True],
       [False, False,  True, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False]])

In [65]:
# if you wants data then

arr1[arr1>50]

# this is called indexing using boolean array or some times its called "filtering".

array([89, 81, 79, 77, 78, 51, 63])

In [66]:
# Q. fatch data greater than 50 and ODD number.

arr1[(arr1>50)&(arr1%2!=0)]      # we don't write 'and' instead we write '&' (ampercent) 

array([89, 81, 79, 77, 51, 63])

In [67]:
# Q. fatch data greater than 50 and EVEN number.

arr1[(arr1>50)&(arr1%2==0)]

array([78])

In [68]:
# Q. make all elements 0 which is greater than 50 and EVEN number.

arr2 = arr1.copy()
arr2[(arr1>50)&(arr1%2==0)] = 0
arr2

array([[89, 36, 81, 79, 77],
       [50, 24,  0, 49,  4],
       [51, 16, 16, 16, 28],
       [63, 23,  6, 11,  9]])

In [72]:
arr3 = np.arange(100)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [121]:
# Q. Find Prime number.

def funt(x):
    count=0
    for i in range(2,(x//2+1)):
        if(x%i == 0):
            count = count+1
            break
    if(count == 0 and x != 1):
        print(x)

for i in arr3:
    funt(i)

0
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
