In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

##### we can perfome Mathematical operaions - (add , sub , mul , delete) on two array's elements.

In [4]:
arr2-arr1

array([3, 3, 3, 3, 3, 3])

In [5]:
arr2+arr1

array([ 5,  7,  9, 11, 13, 15])

In [6]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [9]:
arr2/arr1

array([4.  , 2.5 , 2.  , 1.75, 1.6 , 1.5 ])

In [10]:
arr1+5

array([ 6,  7,  8,  9, 10, 11])

In [11]:
arr2*2

array([ 8, 10, 12, 14, 16, 18])

In [13]:
# conditions check
arr2>6

# false if less than 6 & True if greater than 6

array([False, False, False,  True,  True,  True])

In [14]:
arr1<4

array([ True,  True,  True, False, False, False])

#### dot product in array(matric)

In [17]:
#create two matrics of 2x3 & 3x2 size.
#so, final matric size are 2x2.

arr3 = np.arange(6).reshape(2,3) 
arr4 = np.arange(6,12).reshape(3,2)

In [18]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
#perform dor product i.e a.b using dot() function
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [21]:
arr1.dot(arr2)

154

In [23]:
arr1.dot(arr3)      # error bcoz matric size not equivalant

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

#### to perform maximun , minimun , sort etc. on array

In [24]:
arr4.max()

11

In [26]:
arr4.min()

6

In [31]:
arr5 = np.array([9,5,2,3,1,0])
arr5.sort()
arr5

array([0, 1, 2, 3, 5, 9])

#### if we find row-wise or col-wise maxi,mini data

In [33]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
arr4.min(axis=0)     #axis=0 means fins col-wise max/min

array([6, 7])

In [36]:
arr4.max(axis=0)

array([10, 11])

In [37]:
arr4.max(axis=1)     #axis=1 means fins row-wise max/min

array([ 7,  9, 11])

In [39]:
arr4.sum()          # sumof elements of whole array

51

In [40]:
arr4.sum(axis=0)     #col-wise sum()

array([24, 27])

In [41]:
arr4.sum(axis=1)     #row-wise sum()

array([13, 17, 21])

In [42]:
arr4.mean()          # mean find

8.5

In [46]:
arr4.std()         #standard deviation

1.707825127659933

In [53]:
np.median(arr4)      # to find median

8.5

In [50]:
np.sin(arr4)       # sin thetha of every data

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [54]:
np.cos(arr4)

array([[ 0.96017029,  0.75390225],
       [-0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ]])

In [57]:
np.exp(arr4)      # exponential

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [58]:
np.log(arr4)     # logs

array([[1.79175947, 1.94591015],
       [2.07944154, 2.19722458],
       [2.30258509, 2.39789527]])

In [59]:
np.sqrt(arr4)    # square root

array([[2.44948974, 2.64575131],
       [2.82842712, 3.        ],
       [3.16227766, 3.31662479]])