In [1]:
import numpy as np

### we Reshape the array using 5 ways :
#### Ravel
#### Reshape
#### Transpose
#### Stacking
#### Splitting

### Reshape() 

In [5]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
arr1.ndim    # it has 2D array

2

### Ravle() - It convert higher Dimension array to 1-D array

In [10]:
arr1.ravel()    # convert 2D into 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Transpose() : change row <-> col

In [11]:
arr1.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

### Stacking() : Use to combine two matrics of same size
#### it has two functions - hstack()  & vstack()

In [12]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
arr2 = np.arange(24,48).reshape(6,4)
arr2

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [27]:
arr3 = np.hstack((arr1,arr2))      #join horizontly two arrays
arr3

array([[ 0,  1,  2,  3, 24, 25, 26, 27],
       [ 4,  5,  6,  7, 28, 29, 30, 31],
       [ 8,  9, 10, 11, 32, 33, 34, 35],
       [12, 13, 14, 15, 36, 37, 38, 39],
       [16, 17, 18, 19, 40, 41, 42, 43],
       [20, 21, 22, 23, 44, 45, 46, 47]])

In [28]:
arr3 = np.vstack((arr1,arr2))      #join verticaly two arrays
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

### Splitting() : split one array into two
#### hsplit()  &  vsplit()

In [30]:
np.hsplit(arr3,4)     # we pass the total no. of cols to split into it   # make 4 arrays of equal size

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20],
        [24],
        [28],
        [32],
        [36],
        [40],
        [44]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21],
        [25],
        [29],
        [33],
        [37],
        [41],
        [45]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22],
        [26],
        [30],
        [34],
        [38],
        [42],
        [46]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23],
        [27],
        [31],
        [35],
        [39],
        [43],
        [47]])]

In [42]:
np.hsplit(arr3,2)      # make 2 arrays of equal size

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21],
        [24, 25],
        [28, 29],
        [32, 33],
        [36, 37],
        [40, 41],
        [44, 45]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23],
        [26, 27],
        [30, 31],
        [34, 35],
        [38, 39],
        [42, 43],
        [46, 47]])]

In [31]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [36]:
np.vsplit(arr3,12)      # we pass the total no. of rows to split into it.

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]]),
 array([[24, 25, 26, 27]]),
 array([[28, 29, 30, 31]]),
 array([[32, 33, 34, 35]]),
 array([[36, 37, 38, 39]]),
 array([[40, 41, 42, 43]]),
 array([[44, 45, 46, 47]])]

In [37]:
np.vsplit(arr3,6)     # make 6 arrays of equal size

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31]]),
 array([[32, 33, 34, 35],
        [36, 37, 38, 39]]),
 array([[40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [38]:
np.vsplit(arr3,4)     # make 4 arrays of equal size

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]),
 array([[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [39]:
np.vsplit(arr3,3)    # make 3 arrays of equal size

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]),
 array([[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [40]:
np.vsplit(arr3,2)        # make 2 arrays of equal size

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]